version: "3"
services:
  recorder:
    image: bililive/recorder:latest
    container_name: recorder
    volumes:
      - /mnt/storage/records:/rec
    restart: unless-stopped
    ports:
      - "2356:2356"
